Feat/next-prev-buttons
Nucleo-Estudantes-Informatica-ISEP/antirecurso pull request #30
Opened 2023-04-23 15:29 UTC by andrefbarros

Notion task: https://www.notion.so/67c560114b234cf38a5ee26dd22362cc?v=91204d54737041399cba233e30b5c015&p=44ed6d2cd54141c894067ef35675ef86&pm=s

Feature:
- Added next and previous buttons when taking an exam and reviewing exams taken
- Added question prompt component
- Added question review component

2023-04-23 21:56 UTC, tomasflopes requested changes

2023-04-23 21:56 UTC, tomasflopes commented on src/app/(guest)/exams/[id]/answer/page.tsx
> +              <QuestionPrompt
Nice refactor!

2023-04-23 21:56 UTC, tomasflopes commented on src/app/(guest)/exams/[id]/answer/page.tsx
> +                <PrimaryButton
Rethink the design, probably two arrow icons on the side of the question numbers would better suit the design.
If you can, make some variations of the approach and annex them to the PR to discuss in the next meeting

2023-04-24 12:40 UTC, andrefbarros commented
Option 1:
![image](https://user-images.githubusercontent.com/103772884/233964409-92abac8d-d6e8-42e0-9452-8f854ef69dbd.png)

Option 2:
![Screenshot from 2023-04-24 10-58-18](https://user-images.githubusercontent.com/103772884/233964635-8aac51d1-fd8c-4989-b47f-f672415846eb.png)

Option 3:
![image](https://user-images.githubusercontent.com/103772884/233976719-a511a4b3-4976-4890-b766-8449b09ca2cc.png)

Option 4:
![image](https://user-images.githubusercontent.com/103772884/233977162-17ed15a3-31db-49bd-91d3-c1924d846ba2.png)

2023-04-24 13:13 UTC, merged