Enchanced/stats
Nucleo-Estudantes-Informatica-ISEP/antirecurso pull request #50
Opened 2023-07-01 15:20 UTC by andrefbarros

Feature: added new Grade calculator. Gives student the grade needed in the exam to obtain their objective in that specific UC)

- General styling fix in desktop or mobile
- Added more explanatory messages

### When user do not fill the grade wanted
![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/103772884/313bb61f-538e-4ff2-ab9d-db7961fd6e1b)

### When user do not fill the frequency grade
![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/103772884/58c38680-8c3f-439e-8020-b6ca4ef61a92)

### When user wants a grade impossible to have according to the frequency grade
![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/103772884/a529ebfe-5a64-4328-b87a-3209b1fff952)

### When user fills each field correctly
![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/103772884/643dd4d6-0a27-407d-aa75-31cdba7e3bba)

2023-07-01 17:42 UTC, tomasflopes requested changes

2023-07-01 17:42 UTC, tomasflopes commented on src/components/GoalGradeCalculator/index.tsx
> +  const finalGradePretended =
rename variable to `finalGradeNeeded`

2023-07-01 17:42 UTC, tomasflopes commented on src/components/GoalGradeCalculator/index.tsx
> +              if (value.match(/^\d{1,}$/)) {
Change this to don't accept decimal places

2023-07-01 17:58 UTC, ricardo177m commented
Great addition!

2023-07-01 18:05 UTC, ricardo177m approved these changes

2023-07-02 14:01 UTC, tomasflopes approved these changes

2023-07-02 14:04 UTC, merged