Update for Issue #47
Nucleo-Estudantes-Informatica-ISEP/antirecurso pull request #53
Opened 2023-07-02 17:37 UTC by MiguelOliveira1200874

**Pull Request: Update for Issue #47**

**Description:**
This pull request addresses Issue #47 by updating the README.md file to provide a more comprehensive and up-to-date overview of the Antirecurso project. The changes made include:

1. Updated the introduction section to provide a clearer and more concise description of the project.
2. Reorganized and expanded the "About the Project" section to provide a better understanding of the evolution of Antirecurso from a mobile app to a comprehensive study platform.
3. Added a new section, "Usage Examples," to provide step-by-step instructions on how to use Antirecurso and included relevant screenshots for better visualization.
4. Updated the "Tech Stack" section to reflect the transition to the Next.js framework and provided a brief explanation of Next.js, Tailwind CSS, and Alpine.js.
5. Updated the "Contributions" section to provide clearer instructions for contributing to the project.
6. Added a new section, "License Information," to provide information about the project's open-source license and the freedoms it provides.
7. Made minor formatting and styling improvements throughout the README.md file.

**Changes Made:**

- Replaced outdated information with updated project details.
- Added step-by-step usage examples with relevant screenshots.
- Updated the tech stack section to reflect the transition to Next.js.
- Added a placeholder table for release updates.
- Clarified and expanded the contribution guidelines.
- Added a new section for license information.
- Made minor formatting and styling improvements.

Please review and let me know if any further changes are required. Thank you!

2023-07-03 18:53 UTC, ricardo177m requested changes

2023-07-03 18:53 UTC, ricardo177m commented on README.md
> +If you're a student seeking extra academic resources, check out "antirecurso" <a href="https://antirecurso.nei-isep.org" target="_blank">here</a>. It's a comprehensive tool for exam preparation.
Change all references of "antirecurso" to Antirecurso (no quotes & uppercase).

2023-07-03 18:53 UTC, ricardo177m commented on README.md
> +- **Alpine.js**: A rugged, minimal framework for composing JavaScript behavior in your markup. It’s like Tailwind for JavaScript.
We do not use Alpine.js anymore; you could instead add a reference to Framer Motion, for example.

2023-07-03 23:30 UTC, MiguelOliveira1200874 commented
@ricardo177m Corrected everything you said and added a RoadMapSection according to some of your instructions https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/pull/53/commits/9766bd0b6d8b98ae3d5f8538d8fad550cd186da0

2023-07-04 00:12 UTC, ricardo177m commented
@MiguelOliveira1200874 Well done! One more thing: we're missing the fork part from the contributions section. Could you please add it and fix a typo in "Contribuitions"?

2023-07-04 10:56 UTC, MiguelOliveira1200874 commented
@ricardo177m Added the Contact Us Section and corrected what you asked for.

PS : Please check the email i sent you on [support.antirecurso@nei-isep.org](mailto:support.antirecurso@nei-isep.org).

2023-07-04 13:35 UTC, ricardo177m commented
LGTM!

2023-07-07 21:13 UTC, merged